[package]
name = "rustplain-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "rustplain"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
rustplain-diag = { version = "0.1.0", path = "../rustplain-diag" }
rustplain-render = { version = "0.1.0", path = "../rustplain-render" }
rustplain-cargo = { version = "0.1.0", path = "../rustplain-cargo" }
