[package]
name = "rustplain-cargo"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Cargo integration for the rustplain diagnostic tool."
readme = "README.md"
repository.workspace = true
homepage.workspace = true

[dependencies]
rustplain-diag = { version = "0.1.0", path = "../rustplain-diag" }
