[package]
name = "orust-emit"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Rust source emitter for ORust programs."
readme = "README.md"
repository.workspace = true
homepage.workspace = true

[dependencies]
orust-syntax = { version = "0.1.0", path = "../orust-syntax" }
