[package]
name = "orust-diag"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Diagnostics and generated-source reporting for ORust."
readme = "README.md"
repository.workspace = true
homepage.workspace = true

[dependencies]
serde_json = "1"
orust-syntax = { version = "0.1.0", path = "../orust-syntax" }
orust-emit = { version = "0.1.0", path = "../orust-emit" }
